export const INGREDIENTS = [
  {
    id: 'psc-collagen',
    name: 'Pepsin-solubilized Collagen (PSC)',
    kind: 'protein',
    prep: 'Descale/defat tilapia skin, acid-swell, pepsin digestion',
    role: 'Structural scaffold (Layer 2/3)',
    lookupName: 'COL1A1',
  },
  {
    id: 'collagen-hydrolysate',
    name: 'Collagen Hydrolysate Peptides',
    kind: 'protein',
    prep: 'Enzymatic hydrolysis (Alcalase/papain) of skin protein, <3kDa fractionation',
    role: 'Bioactive nano-inclusion',
    lookupName: 'COL1A1',
  },
  {
    id: 'marine-pufas',
    name: 'Marine PUFAs (EPA/DHA)',
    kind: 'compound',
    prep: 'Lipid extraction (Folch/Bligh-Dyer), separate from protein fraction',
    role: 'Bioactive nano-inclusion',
    lookupName: 'docosahexaenoic acid',
  },
  {
    id: 'lmw-ha',
    name: 'LMW-Hyaluronic Acid',
    kind: 'compound',
    prep: 'Purified, <500 kDa',
    role: 'Polymer backbone (Layer 1)',
    lookupName: 'hyaluronic acid',
  },
  {
    id: 'fibrinogen',
    name: 'Dried Fibrinogen',
    kind: 'protein',
    prep: 'Purified, dried',
    role: 'Haemostatic anchor (Layer 2)',
    lookupName: 'FGA',
  },
  {
    id: 'curcumin',
    name: 'Curcumin',
    kind: 'compound',
    prep: 'Botanical extract',
    role: 'Phytochemical modulator',
    lookupName: 'curcumin',
  },
  {
    id: 'baicalein',
    name: 'Baicalein',
    kind: 'compound',
    prep: 'TCM botanical extract',
    role: 'Phytochemical modulator',
    lookupName: 'baicalein',
  },
  {
    id: 'astragalus-iv',
    name: 'Astragalus (AS-IV)',
    kind: 'compound',
    prep: 'Botanical extract',
    role: 'Phytochemical modulator',
    lookupName: 'astragaloside IV',
  },
  {
    id: 'ag-nanoparticles',
    name: 'Ag nanoparticles (low-dose)',
    kind: 'compound',
    prep: 'In-situ reduction or pre-formed AgNP, sub-cytotoxic loading',
    role: 'Antimicrobial',
    lookupName: 'silver',
  },
];
